const DATA_URL='./outputs/meiyou_periods_draft.csv';
const STORE_KEY='period-helper-state-v1',SETTINGS_KEY='period-helper-settings-v1',JOURNAL_KEY='period-journals-v1',JOURNAL_PENDING_KEY='period-journals-pending-v1',SYNC_PENDING_KEY='period-helper-sync-pending-v1';
const DEVICE_TOKEN_KEY='period-sync-device-token-v1',DEVICE_TOKEN_EXPIRY_KEY='period-sync-device-expiry-v1',SYNC_LOG_KEY='period-sync-safe-log-v1';
const SYNC_URL=String(globalThis.PERIOD_SYNC_URL||'').replace(/\/$/,'');
const DAY=86400000,labels5=['很低','偏低','一般','较好','很好'];
const fmt=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric'}),fullFmt=new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric'});
const iso=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);
const parseDate=s=>new Date(`${s}T12:00:00`),days=(a,b)=>Math.round((parseDate(b)-parseDate(a))/DAY),addDays=(s,n)=>{const d=parseDate(s);d.setDate(d.getDate()+n);return iso(d)};
const median=a=>{const s=[...a].sort((x,y)=>x-y);return s.length?s[Math.floor(s.length/2)]:0},mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0,clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const nowIso=()=>new Date().toISOString(),monthOf=date=>date.slice(0,7),inRange=(d,a,b)=>d>=a&&d<=b;

let basePeriods=[],calendarCursor=new Date(),calendarMode='month',selectedDate=iso(new Date()),editingPeriod=null,deferredInstall,syncTimer,journalTimer;
let state=normalizeState(JSON.parse(localStorage.getItem(STORE_KEY)||'{}'));
let journals=normalizeJournals(JSON.parse(localStorage.getItem(JOURNAL_KEY)||'{}'));
localStorage.removeItem(JOURNAL_KEY);localStorage.removeItem(JOURNAL_PENDING_KEY);journals=normalizeJournals();
let settings={lifeStage:'regular',ownerNotify:true,partnerNotify:true,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')};

function normalizeState(v={}){const allowed=['mood','energy','sleep','activity','stress','pain','symptoms','temperature','updatedAt'],logs=Object.fromEntries(Object.entries(v.logs&&typeof v.logs==='object'?v.logs:{}).map(([date,log])=>[date,Object.fromEntries(allowed.filter(k=>log?.[k]!==undefined).map(k=>[k,log[k]]))]));return {periods:Array.isArray(v.periods)?v.periods:[],logs,tombstones:{periods:v.tombstones?.periods||{},logs:v.tombstones?.logs||{}}}}
function normalizeJournals(v={}){return {entries:v.entries&&typeof v.entries==='object'?v.entries:{},tombstones:v.tombstones&&typeof v.tombstones==='object'?v.tombstones:{}}}
async function loadBase(){const text=await fetch(DATA_URL).then(r=>{if(!r.ok)throw new Error('历史数据载入失败');return r.text()});const lines=text.trim().split(/\r?\n/),head=lines.shift().split(',');basePeriods=lines.map(line=>Object.fromEntries(head.map((h,i)=>[h,line.split(',')[i]||''])))}
function allPeriods(){const today=iso(new Date()),replaced=new Set(state.periods.map(p=>p.originalStart).filter(Boolean)),map=new Map(basePeriods.filter(p=>!replaced.has(p.period_start)).map(p=>[p.period_start,{start:p.period_start,end:p.period_end,type:'period',source:'美柚截图',status:p.status,base:true}]));state.periods.filter(p=>p.type==='period'&&p.status!=='deleted').forEach(p=>map.set(p.start,p.status==='ongoing'?{...p,end:today}:p));return [...map.values()].sort((a,b)=>a.start.localeCompare(b.start))}
function cycleModel(){const ps=allPeriods(),intervals=ps.slice(0,-1).map((p,i)=>({...p,length:days(p.start,ps[i+1].start)})),valid=intervals.filter(x=>x.length>=15&&x.length<=60),recent=valid.slice(-12),weighted=[];recent.forEach((x,i)=>{const w=i>=recent.length-3?3:i>=recent.length-6?2:1;for(let j=0;j<w;j++)weighted.push(x.length)});const center=Math.round(median(weighted)||29),deviations=recent.map(x=>Math.abs(x.length-center));let spread=Math.max(2,Math.ceil(median(deviations)*1.5));if(settings.lifeStage==='menarche')spread=Math.max(5,spread+2);if(settings.lifeStage==='perimenopause')spread=Math.max(7,spread+4);const last=ps.at(-1),next=addDays(last.start,center);return {ps,intervals,center,spread,next,windowStart:addDays(next,-spread),windowEnd:addDays(next,spread),last,confidence:recent.length>=6&&spread<=4?'较高':recent.length>=3?'中等':'较低'}}
function phaseForDate(date,m=cycleModel()){if(m.ps.some(p=>inRange(date,p.start,p.end)))return'period';const starts=m.ps.map(p=>p.start).sort(),next=starts.find(s=>s>date)||m.next;if(inRange(date,addDays(next,-16),addDays(next,-12)))return'ovulation';if(inRange(date,addDays(next,-7),addDays(next,-1)))return'pms';return'follicular'}
function phaseInfo(date=iso(new Date())){const m=cycleModel(),key=phaseForDate(date,m),names={period:'月经期',follicular:'卵泡期',ovulation:'排卵期',pms:'黄体期'};return {...m,date,key,name:names[key],cycleDay:days(m.last.start,date)+1,ovulation:addDays(m.next,-14),pmsStart:addDays(m.next,-7)}}

function saveLocal({sync=true}={}){localStorage.setItem(STORE_KEY,JSON.stringify(state));if(sync){localStorage.setItem(SYNC_PENDING_KEY,'yes');scheduleSync()}renderAll()}
function saveJournals({sync=true}={}){localStorage.setItem(JOURNAL_KEY,JSON.stringify(journals));if(sync){localStorage.setItem(JOURNAL_PENDING_KEY,'yes');scheduleJournalSync()}renderAll()}
function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));localStorage.setItem(SYNC_PENDING_KEY,'yes');scheduleSync()}
function periodKey(p){return p.id||`${p.start}|${p.type||'period'}`}
function prioritizePeriods(records){return [...records].sort((a,b)=>Number(a.base)-Number(b.base)||Number(b.status==='ongoing')-Number(a.status==='ongoing')||b.updatedAt?.localeCompare(a.updatedAt||'')||0)}
function periodsForDate(date){return prioritizePeriods(allPeriods().filter(p=>inRange(date,p.start,p.end)))}
function periodForDate(date){return periodsForDate(date)[0]||null}
function recentPeriod(){const today=iso(new Date()),last=allPeriods().at(-1);return last&&days(last.end,today)>=0&&days(last.end,today)<=14?last:null}
function newer(a,b){return String(a||'')>=String(b||'')}
function mergeMap(a={},b={}){const out={...a};Object.entries(b).forEach(([k,v])=>{if(!out[k]||newer(v,out[k]))out[k]=v});return out}
function mergeUserState(local,remote){local=normalizeState(local);remote=normalizeState(remote);const tombstones={periods:mergeMap(local.tombstones.periods,remote.tombstones.periods),logs:mergeMap(local.tombstones.logs,remote.tombstones.logs)},periods=new Map();[...remote.periods,...local.periods].forEach(p=>{const k=periodKey(p),old=periods.get(k);if(!old||newer(p.updatedAt,old.updatedAt))periods.set(k,p)});for(const[k,p]of periods)if(tombstones.periods[k]&&newer(tombstones.periods[k],p.updatedAt))periods.delete(k);const logs={...remote.logs};Object.entries(local.logs).forEach(([d,l])=>{if(!logs[d]||newer(l.updatedAt,logs[d].updatedAt))logs[d]=l});Object.entries(logs).forEach(([d,l])=>{if(tombstones.logs[d]&&newer(tombstones.logs[d],l.updatedAt))delete logs[d]});return {periods:[...periods.values()],logs,tombstones}}
function mergeJournalState(local,remote){local=normalizeJournals(local);remote=normalizeJournals(remote);const tombstones=mergeMap(local.tombstones,remote.tombstones),entries={...remote.entries};Object.entries(local.entries).forEach(([d,e])=>{if(!entries[d]||newer(e.updatedAt,entries[d].updatedAt))entries[d]=e});Object.entries(entries).forEach(([d,e])=>{if(tombstones[d]&&newer(tombstones[d],e.updatedAt))delete entries[d]});return {entries,tombstones}}

function setSync(text,status='idle'){const badge=document.querySelector('#syncBadge');badge.textContent=text;badge.dataset.state=status}
function alertSystem(message='',level='warning'){const el=document.querySelector('#systemAlert');el.textContent=message;el.dataset.level=level;el.hidden=!message}
function safeLog(operation,status){let logs=[];try{logs=JSON.parse(localStorage.getItem(SYNC_LOG_KEY)||'[]')}catch{}logs.push({at:nowIso(),operation,status:String(status).slice(0,80)});localStorage.setItem(SYNC_LOG_KEY,JSON.stringify(logs.slice(-20)))}
async function authorizeDevice(password){const r=await fetch(`${SYNC_URL}/authorize`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password})}),x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||'设备验证失败');localStorage.setItem(DEVICE_TOKEN_KEY,x.deviceToken);localStorage.setItem(DEVICE_TOKEN_EXPIRY_KEY,x.expiresAt);localStorage.setItem('period-editor-device','yes');return x.deviceToken}
async function deviceToken(){const token=localStorage.getItem(DEVICE_TOKEN_KEY),exp=localStorage.getItem(DEVICE_TOKEN_EXPIRY_KEY);if(token&&exp&&Date.parse(exp)>Date.now()+60000)return token;localStorage.removeItem(DEVICE_TOKEN_KEY);localStorage.removeItem(DEVICE_TOKEN_EXPIRY_KEY);const password=prompt('此设备首次同步：请输入共享编辑口令（验证成功后180天内无需重复输入）')||'';return password?authorizeDevice(password):''}
async function pullRemote(){if(!SYNC_URL||!navigator.onLine)return;try{setSync('正在同步…');const r=await fetch(`${SYNC_URL}/state`,{cache:'no-store'}),x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||'读取失败');state=mergeUserState(state,x.state);localStorage.setItem(STORE_KEY,JSON.stringify(state));if(x.state?.settings&&localStorage.getItem(SYNC_PENDING_KEY)!=='yes'){settings={...settings,...x.state.settings};localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings))}setSync(localStorage.getItem(SYNC_PENDING_KEY)==='yes'?'等待写回':'已与 GitHub 同步',localStorage.getItem(SYNC_PENDING_KEY)==='yes'?'idle':'ok')}catch(e){safeLog('pull',e.name||'failed');setSync('同步读取失败','error');alertSystem('云端读取失败；本机记录仍可使用，联网后会重试。','danger')}}
function scheduleSync(){clearTimeout(syncTimer);syncTimer=setTimeout(syncNow,650)}
async function syncNow(){if(!SYNC_URL)return;if(!navigator.onLine)return setSync('离线保存');try{const token=await deviceToken();if(!token)return setSync('等待设备验证');setSync('正在同步…');const r=await fetch(`${SYNC_URL}/sync`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({schemaVersion:1,mutationId:crypto.randomUUID(),state:{...state,settings:{lifeStage:settings.lifeStage,ownerNotify:settings.ownerNotify,partnerNotify:settings.partnerNotify}}})}),x=await r.json();if(!r.ok||!x.ok){if(r.status===401){localStorage.removeItem(DEVICE_TOKEN_KEY);localStorage.removeItem(DEVICE_TOKEN_EXPIRY_KEY)}throw new Error(x.error||'同步失败')}state=mergeUserState(state,x.state);localStorage.setItem(STORE_KEY,JSON.stringify(state));localStorage.removeItem(SYNC_PENDING_KEY);setSync('已与 GitHub 同步','ok');safeLog('sync','ok');alertSystem('')}catch(e){localStorage.setItem(SYNC_PENDING_KEY,'yes');safeLog('sync',e.name||'failed');setSync('同步失败','error');alertSystem(`同步失败：${e.message}。数据仍在本机。`,'danger')}}
async function checkStatus(){if(!SYNC_URL||!navigator.onLine)return;try{const r=await fetch(`${SYNC_URL}/status`,{cache:'no-store'}),x=await r.json();if(!r.ok||!x.githubOk)throw new Error();if(x.tokenDaysRemaining<=30)alertSystem(`GitHub Token 将在 ${x.tokenExpiresAt} 到期，剩余约 ${x.tokenDaysRemaining} 天。`,x.tokenDaysRemaining<=7?'danger':'warning')}catch{safeLog('status','failed')}}

function renderAll(){renderHero();renderSnapshot();renderAdvice();renderCalendarEnhanced();renderHistory();renderInsights();renderEmailPreview();renderSettings()}
function renderHero(){const p=phaseInfo(),today=iso(new Date()),hints={period:'经血阶段',follicular:'经后恢复阶段',ovulation:'排卵估算窗口',pms:'经前准备阶段'},log=state.logs[today]||{},ongoing=state.periods.find(x=>x.type==='period'&&x.status==='ongoing'),periodButton=document.querySelector('#startPeriodBtn'),editButton=document.querySelector('#editCurrentPeriodBtn'),cancelButton=document.querySelector('#cancelCurrentPeriodBtn'),recent=ongoing||recentPeriod(),cancellable=ongoing||(!recent?.base?recent:null);document.querySelector('#phaseRingName').textContent=p.name;document.querySelector('#phaseRingHint').textContent='';document.querySelector('#cycleRing').className=`cycle-ring phase-${p.key}`;document.querySelector('#phasePill').textContent=hints[p.key];document.querySelector('#phasePill').className=`phase-pill phase-${p.key}`;document.querySelector('#todayDate').textContent=fullFmt.format(parseDate(today));document.querySelector('#todayHeadline').textContent=adviceFor(p,log)[0];document.querySelector('#daysToPeriod').textContent=`${Math.max(0,days(today,p.next))} 天`;document.querySelector('#expectedDate').textContent=fmt.format(parseDate(p.next));document.querySelector('#predictionRange').textContent=`${fmt.format(parseDate(p.windowStart))}–${fmt.format(parseDate(p.windowEnd))}`;periodButton.textContent=ongoing?'月经结束':'月经开始';periodButton.dataset.periodState=ongoing?'end':'start';editButton.hidden=!recent;editButton.textContent=ongoing?'编辑开始日期':'编辑最近一次';cancelButton.hidden=!cancellable;cancelButton.textContent=ongoing?'取消误记':'取消最近一次'}
function renderSnapshot(){const log=state.logs[iso(new Date())],items=log?[[`${labels5[Number(log.mood)-1]||'—'}`,'情绪'],[`${labels5[Number(log.energy)-1]||'—'}`,'精力'],[`${labels5[Number(log.sleep)-1]||'—'}`,'睡眠'],[`${log.pain??0}/10`,'疼痛']]:[['未记录','情绪'],['未记录','精力'],['未记录','睡眠'],['未记录','疼痛']];document.querySelector('#todaySnapshot').innerHTML=items.map(([v,l])=>`<button class="snapshot" data-open-log><small>${l}</small><strong>${v}</strong></button>`).join('')}
function adviceFor(p,log={}){const base={period:['根据身体感受降低运动强度，轻柔步行和伸展通常比强撑更合适。','规律进食并补充水分，工作安排尽量留出缓冲。'],follicular:['精力可能逐步恢复，可把复杂工作分批安排。','逐渐恢复力量或有氧活动，以第二天不过度疲劳为准。'],ovulation:['这是日历法估算窗口，不代表已经确认排卵，也不能用于避孕保证。','维持正常作息和活动，不必为了周期阶段强行改变计划。'],pms:['为睡眠和临时变化预留空间，减少连续高压或过晚安排。','如果以往此时容易嗜睡或烦躁，可提前和伴侣沟通希望得到的支持。']}[p.key];if(Number(log.sleep)<=2)base.unshift('今天睡眠记录偏低，优先补足休息，再决定运动和工作强度。');if(Number(log.pain)>=6)base.unshift('今天疼痛记录较高，建议减少勉强活动并持续观察。');return base.slice(0,3)}
function renderAdvice(){const p=phaseInfo(),log=state.logs[p.date]||{},s=log.symptoms||[],base={period:{title:'月经期 · 温和照护',observation:'传统调养通常重视经血排出期间的保暖、休息与饮食规律。',tips:['按实际体力降低运动强度，选择散步或轻柔伸展。','吃温热、易消化且营养均衡的正餐，补充水分，避免因阶段标签过度忌口。']},follicular:{title:'卵泡期 · 经后恢复',observation:'月经刚结束后可视为逐步恢复阶段，重点观察精力、食欲和睡眠是否回升。',tips:['规律摄入蛋白质、含铁食物与蔬果，以日常均衡饮食为主。','运动和工作量逐步恢复，以第二天没有明显疲劳为尺度。']},ovulation:{title:'排卵期 · 平稳维持',observation:'当前只是日历推算的排卵窗口，可结合分泌物和基础体温继续观察，但不能据此确认排卵。',tips:['保持饮水、睡眠和正常饮食，不必为了阶段强行进补。','精力允许时维持常规运动；出现不适就及时降低强度。']},pms:{title:'黄体期 · 经前准备',observation:'经前阶段可留意睡眠、情绪、食欲和腹胀是否呈现个人重复模式。',tips:['规律三餐并为睡眠留出缓冲，减少连续熬夜和高压安排。','若咖啡因、酒精或重口味会加重个人不适，可按自己的记录适量减少。']}}[p.key];const extras=[];if(s.includes('怕冷')&&Number(log.energy)<=2)extras.push('怕冷与疲乏同时出现可作为偏虚寒倾向的观察线索；可选择温热熟食，若持续或明显加重应咨询专业人员。');if(s.includes('烦躁')||s.includes('情绪敏感'))extras.push('记录到烦躁或情绪敏感，可安排舒缓步行、拉伸或呼吸练习，并减少连续高压任务；单凭情绪不能确定证候。');document.querySelector('#dailyAdvice').innerHTML=`<div class="advice-list">${adviceFor(p,log).map(x=>`<div class="advice-item">${x}</div>`).join('')}</div>`;document.querySelector('#tcmPhaseTitle').textContent=base.title;document.querySelector('#tcmPhaseDot').className=`phase-dot phase-${p.key}`;document.querySelector('#tcmAdvice').innerHTML=`<p>${base.observation}</p><div class="advice-list">${[...base.tips,...extras].map(x=>`<div class="advice-item">${x}</div>`).join('')}</div>`}
function renderCalendar(){const y=calendarCursor.getFullYear(),mo=calendarCursor.getMonth(),first=new Date(y,mo,1),start=new Date(y,mo,1-first.getDay()),p=phaseInfo(),today=iso(new Date());document.querySelector('#calendarTitle').textContent=`${y}年${mo+1}月`;let html='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=iso(d),classes=['day',`phase-${phaseForDate(key)}`];if(d.getMonth()!==mo)classes.push('outside');if(key===today)classes.push('today');if(allPeriods().some(x=>inRange(key,x.start,x.end)))classes.push('recorded');else if(inRange(key,p.windowStart,p.windowEnd))classes.push('predicted');if(inRange(key,p.pmsStart,addDays(p.next,-1)))classes.push('pms');if(inRange(key,addDays(p.ovulation,-2),addDays(p.ovulation,2)))classes.push('ovulation');if(journals.entries[key])classes.push('has-journal');html+=`<button class="${classes.join(' ')}" data-date="${key}" aria-label="${key}"><span class="day-number">${d.getDate()}</span></button>`}document.querySelector('#calendarGrid').innerHTML=html}
function renderHistory(){const m=cycleModel(),ps=m.ps,items=m.intervals,values=items.map(x=>x.length),w=Math.max(640,items.length*22),h=250,pad=32,min=15,max=45,x=i=>pad+i*((w-pad*2)/Math.max(1,items.length-1)),y=v=>pad+(max-clamp(v,min,max))*((h-pad*2)/(max-min)),points=items.map((d,i)=>`${x(i)},${y(d.length)}`).join(' '),dots=items.map((d,i)=>`<circle cx="${x(i)}" cy="${y(d.length)}" r="6" tabindex="0" role="button" data-cycle-index="${i}" class="${d.length<21||d.length>35?'unusual':''}"><title>${d.start}：${d.length}天</title></circle>`).join('');document.querySelector('#historyCount').textContent=`${ps.length} 次记录`;document.querySelector('#cycleHistoryChart').innerHTML=items.length?`<svg viewBox="0 0 ${w} ${h}" width="${w}" height="${h}" aria-label="全部历史周期长度，点击圆点查看详情"><rect x="${pad}" y="${y(35)}" width="${w-pad*2}" height="${y(21)-y(35)}" class="normal-band"/><line x1="${pad}" y1="${y(21)}" x2="${w-pad}" y2="${y(21)}"/><line x1="${pad}" y1="${y(35)}" x2="${w-pad}" y2="${y(35)}"/><text x="4" y="${y(35)+4}">35</text><text x="4" y="${y(21)+4}">21</text><polyline points="${points}"/>${dots}</svg>`:'<p class="muted">周期数据不足。</p>';const recent=values.slice(-12),previous=values.slice(-24,-12),outside=values.filter(v=>v<21||v>35).length,delta=previous.length?mean(recent)-mean(previous):0,trend=!previous.length?'还没有足够的前一阶段数据可比较':Math.abs(delta)<1?'近12次与前12次平均长度基本持平':`近12次平均比前12次${delta>0?'长':'短'} ${Math.abs(delta).toFixed(1)} 天`;document.querySelector('#historyAnalysis').innerHTML=`<div><strong>${median(recent)} 天</strong><span>近12次中位数</span></div><div><strong>${Math.min(...recent)}–${Math.max(...recent)} 天</strong><span>近12次范围</span></div><div><strong>${outside} 次</strong><span>历史中在21–35天外</span></div><p>${trend}。浅色区域表示21–35天参考带，橙色点表示落在范围外；这是数据描述，不是诊断。</p>`;document.querySelector('#historyList').innerHTML=[...ps].reverse().slice(0,12).map((p,idx)=>{const ri=ps.length-1-idx,cycle=ri<ps.length-1?days(p.start,ps[ri+1].start):'—';return `<div class="history-row"><strong>${p.start} → ${p.end}</strong><span>经期 ${days(p.start,p.end)+1} 天</span><span>周期 ${cycle} 天</span><button class="edit-period soft compact" data-start="${p.start}">编辑</button></div>`}).join('')}
function renderInsights(){const m=cycleModel(),cycles=m.intervals.map(x=>x.length),recent=cycles.slice(-12),periodDays=m.ps.map(p=>days(p.start,p.end)+1),stats=[[`${median(cycles)}天`,'全部中位周期'],[`${mean(recent).toFixed(1)}天`,'近12次平均'],[`${Math.min(...recent)}–${Math.max(...recent)}天`,'近12次范围'],[`${mean(periodDays.slice(-12)).toFixed(1)}天`,'近12次经期']];document.querySelector('#summaryStats').innerHTML=stats.map(([v,l])=>`<div class="stat"><strong>${v}</strong><span>${l}</span></div>`).join('');document.querySelector('#cycleChart').innerHTML=m.intervals.slice(-36).map(x=>`<div class="bar ${x.length<21||x.length>35?'unusual':''}" style="height:${clamp((x.length-15)*8,20,210)}px" data-label="${x.start} · ${x.length}天"></div>`).join('');const logs=Object.entries(state.logs),groups={period:[],follicular:[],ovulation:[],pms:[]};logs.forEach(([d,l])=>groups[phaseForDate(d,m)].push(l));document.querySelector('#moodInsight').innerHTML=logs.length<6?needMore(logs.length,6):phaseAverages(groups,'mood');document.querySelector('#lifestyleInsight').innerHTML=logs.length<6?needMore(logs.length,6):['sleep','energy','activity'].map(k=>`<div class="insight-line">${{sleep:'睡眠',energy:'精力',activity:'活动'}[k]}：${bestPhase(groups,k)}</div>`).join('');const unusual=m.intervals.filter(x=>x.length<21||x.length>35);document.querySelector('#qualityInsight').innerHTML=`<p>历史中有 <strong>${unusual.length}</strong> 个周期开始间隔在21–35天之外。橙色柱为需要留意的历史变化。</p><p class="muted">样本：${m.intervals.length}个周期；观察不构成医疗判断。预测使用稳健中位数，降低单次极端值影响。</p>`}
function needMore(have,need){return`<p class="muted">目前有${have}天记录，再记录${need-have}天后开始显示初步个人模式；跨3个周期后更有参考意义。</p>`}
function phaseAverages(g,key){const names={period:'月经期',follicular:'卵泡期',ovulation:'排卵期（估算）',pms:'黄体期'};return Object.entries(g).filter(([,a])=>a.length).map(([k,a])=>`<div class="insight-line">${names[k]}：${mean(a.map(x=>Number(x[key])||3)).toFixed(1)}/5（${a.length}条）</div>`).join('')}
function bestPhase(g,key){const e=Object.entries(g).filter(([,a])=>a.length).map(([k,a])=>[k,mean(a.map(x=>Number(x[key])||3))]).sort((a,b)=>b[1]-a[1]),names={period:'月经期',follicular:'卵泡期',ovulation:'排卵期（估算）',pms:'黄体期'};return e.length?`${names[e[0][0]]}相对较高（${g[e[0][0]].length}条）`:'数据不足'}
function phaseName(k){return({period:'月经期',follicular:'卵泡期',ovulation:'排卵期（估算）',pms:'黄体期'})[k]||'其他阶段'}
function renderEmailPreview(){const p=phaseInfo(),symptoms=state.logs[p.date]?.symptoms||[];document.querySelector('#emailPreview').innerHTML=`主题：明天可能进入${p.key==='period'?'经期':'周期提醒阶段'}<br><br>预计范围：${p.windowStart}–${p.windowEnd}<br>可选症状摘要：${symptoms.length?symptoms.join('、'):'无'}<br><br>建议：先询问需要什么支持，不对情绪作确定判断。`}
function renderSettings(){document.querySelector('#lifeStage').value=settings.lifeStage;document.querySelector('#ownerNotify').checked=settings.ownerNotify;document.querySelector('#partnerNotify').checked=settings.partnerNotify;document.querySelector('#offlineStatus').textContent=navigator.onLine?'当前在线；所有编辑仍会先保存到本机，再同步GitHub。':'当前离线；记录和随笔仍可使用，联网后自动重试。';const installed=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;document.querySelector('#installStatus').textContent=installed?'已作为App安装并独立运行。':'尚未检测到安装。iPhone：Safari分享→添加到主屏幕；Android：点击页面顶部安装。';const token=localStorage.getItem(DEVICE_TOKEN_KEY),exp=localStorage.getItem(DEVICE_TOKEN_EXPIRY_KEY);document.querySelector('#deviceStatus').textContent=token&&exp?`本设备已验证，有效至 ${new Date(exp).toLocaleDateString('zh-CN')}`:'本设备尚未验证；首次在线保存时输入一次口令。';let logs=[];try{logs=JSON.parse(localStorage.getItem(SYNC_LOG_KEY)||'[]')}catch{}document.querySelector('#safeLog').innerHTML=logs.length?[...logs].reverse().map(l=>`<div>${escapeHtml(l.at)} · ${escapeHtml(l.operation)} · ${escapeHtml(l.status)}</div>`).join(''):'暂无失败日志。日志不会记录症状、随笔、口令或Token。'}

function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'',`#${id}`)}
function showToast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function openDialog(id){document.querySelector(id).showModal()}
function closeDialog(el){el.closest('dialog').close()}
function openLog(date=iso(new Date())){selectedDate=date;const f=document.querySelector('#dailyForm'),l=state.logs[date]||{},optional=document.querySelector('#optionalFields'),toggle=document.querySelector('#optionalToggle');f.reset();f.elements.date.value=date;['mood','energy','sleep','pain','activity','stress','temperature'].forEach(k=>{if(l[k]!==undefined&&f.elements[k])f.elements[k].value=l[k]});f.querySelectorAll('[name=symptom]').forEach(i=>i.checked=(l.symptoms||[]).includes(i.value));optional.hidden=true;toggle.setAttribute('aria-expanded','false');toggle.querySelector('.optional-toggle-icon').textContent='＋';document.querySelector('#logDialogTitle').textContent=`${fmt.format(parseDate(date))}感觉怎么样？`;document.querySelector('#deleteLogBtn').hidden=!state.logs[date];openDialog('#logDialog')}
function openPeriodEditor(period=null,{mode='edit',date=iso(new Date())}={}){editingPeriod=period;const f=document.querySelector('#periodForm'),title=document.querySelector('#periodDialogTitle'),hint=document.querySelector('#periodDialogHint');f.reset();f.elements.mode.value=mode;f.elements.id.value=period?.id||'';f.elements.originalStart.value=period?.originalStart||(period?.base?period.start:'');f.elements.start.value=period?.start||date;f.elements.end.value=period?(period.status==='ongoing'&&mode!=='end'?'':period.end):(mode==='start'&&date===iso(new Date())?'':date);f.elements.type.value=period?.type||'period';if(mode==='start'){title.textContent='月经开始';hint.textContent='确认开始日期后保存；误点不会直接写入。'}else if(mode==='end'){title.textContent='月经结束';f.elements.end.value=iso(new Date());hint.textContent=`本次从 ${period.start} 开始，请确认结束日期。`}else{title.textContent='编辑本次月经';hint.textContent=period?.base?'修改会覆盖美柚导入的这次记录，原始 CSV 不会被改写。':'可修改开始、结束日期，也可以删除误记。'}document.querySelector('#deletePeriodBtn').hidden=!period;openDialog('#periodDialog')}
function showDay(date){selectedDate=date;const p=phaseForDate(date),l=state.logs[date],records=periodsForDate(date),period=records[0],source=period?(period.base?'美柚导入':'本设备新增'):'';editingPeriod=period;document.querySelector('#dayDialogTitle').textContent=fullFmt.format(parseDate(date));document.querySelector('#dayDialogBody').innerHTML=`<div class="status-box"><strong>${phaseName(p)}</strong>${period?`<br>月经记录：${period.start}–${period.end}<br><small>${source}${period.status==='ongoing'?' · 尚未结束':''}</small>`:''}</div>${records.length>1?`<p class="period-overlap-note">这一天有 ${records.length} 条重叠记录，当前优先显示本设备新增记录；取消后会显示原来的历史记录。</p>`:''}${l?`<p>情绪 ${labels5[l.mood-1]} · 睡眠 ${labels5[l.sleep-1]} · 疼痛 ${l.pain}/10</p><p>${(l.symptoms||[]).join('、')||'无症状标签'}</p>`:'<p class="muted">当天没有身体状态记录。</p>'}`;document.querySelector('#daySetPeriodBtn').hidden=!!period;document.querySelector('#dayEditPeriodBtn').hidden=!period;document.querySelector('#dayCancelPeriodBtn').hidden=!period;openDialog('#dayDialog')}
function removePeriodRecord(period){const before=JSON.parse(JSON.stringify(state)),existing=period.id&&state.periods.find(p=>p.id===period.id);if(existing){if(existing.originalStart){existing.status='deleted';existing.updatedAt=nowIso()}else{state.periods=state.periods.filter(p=>p.id!==existing.id);state.tombstones.periods[existing.id]=nowIso()}}else if(period.base){state.periods.push({id:crypto.randomUUID(),start:period.start,end:period.end,type:'period',source:'本设备',status:'deleted',originalStart:period.start,updatedAt:nowIso()})}saveLocal();const remains=periodsForDate(selectedDate).length>0;showUndo(remains?'误触记录已取消；该日期仍属于另一条历史经期':'月经记录已取消',()=>{state=before;saveLocal()})}

document.addEventListener('click',async e=>{const nav=e.target.closest('[data-view]');if(nav)return showView(nav.dataset.view);if(e.target.closest('[data-open-log]'))return openLog();if(e.target.closest('.close-dialog'))return closeDialog(e.target);const action=e.target.closest('[data-action]')?.dataset.action;if(action){document.querySelector('#quickDialog').close();if(action==='log')openLog();if(action==='period')openPeriodEditor(null,{mode:'start'})}const day=e.target.closest('.day[data-date]');if(day)showDay(day.dataset.date);const journal=e.target.closest('[data-journal-date]');if(journal)openJournal(journal.dataset.journalDate)});
document.querySelector('#quickAddBtn').addEventListener('click',()=>openDialog('#quickDialog'));
document.querySelector('#startPeriodBtn').addEventListener('click',()=>{const ongoing=state.periods.find(x=>x.type==='period'&&x.status==='ongoing');openPeriodEditor(ongoing||null,{mode:ongoing?'end':'start'})});
document.querySelector('#editCurrentPeriodBtn').addEventListener('click',()=>{const period=state.periods.find(x=>x.type==='period'&&x.status==='ongoing')||recentPeriod();if(period)openPeriodEditor(period)});
document.querySelector('#cancelCurrentPeriodBtn').addEventListener('click',()=>{const ongoing=state.periods.find(x=>x.type==='period'&&x.status==='ongoing'),recent=recentPeriod(),period=ongoing||(!recent?.base?recent:null);if(period&&confirm(`取消 ${period.start} 开始的月经记录？`))removePeriodRecord(period)});
document.querySelector('#periodForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const f=new FormData(e.currentTarget),start=f.get('start'),rawEnd=f.get('end'),end=rawEnd||start,mode=f.get('mode');if(end<start)return showToast('结束日期不能早于开始日期');if(days(start,end)>30)return showToast('一次月经记录不能超过30天');const conflict=allPeriods().find(p=>{const same=editingPeriod&&((editingPeriod.id&&p.id===editingPeriod.id)||(editingPeriod.base&&p.base&&p.start===editingPeriod.start));return !same&&start<=p.end&&end>=p.start});if(conflict)return showToast(`日期与 ${conflict.start} 开始的记录重叠`);const keepOngoing=(mode==='start'&&start===iso(new Date())&&!rawEnd)||(editingPeriod?.status==='ongoing'&&mode==='edit'&&!rawEnd),record={id:f.get('id')||crypto.randomUUID(),start,end,type:f.get('type'),source:'本设备',status:keepOngoing?'ongoing':'confirmed',updatedAt:nowIso()};const originalStart=f.get('originalStart');if(originalStart)record.originalStart=originalStart;const index=state.periods.findIndex(p=>p.id===record.id);if(index>=0)state.periods[index]=record;else state.periods.push(record);document.querySelector('#periodDialog').close();saveLocal();showToast(keepOngoing?'已记录月经开始':'月经日期已保存')});
document.querySelector('#deletePeriodBtn').addEventListener('click',()=>{if(!editingPeriod||!confirm(`取消 ${editingPeriod.start} 开始的整次月经记录？`))return;document.querySelector('#periodDialog').close();removePeriodRecord(editingPeriod)});
document.querySelector('#daySetPeriodBtn').addEventListener('click',()=>{document.querySelector('#dayDialog').close();openPeriodEditor(null,{mode:'start',date:selectedDate})});
document.querySelector('#dayEditPeriodBtn').addEventListener('click',()=>{const period=editingPeriod;document.querySelector('#dayDialog').close();if(period)openPeriodEditor(period)});
document.querySelector('#dayCancelPeriodBtn').addEventListener('click',()=>{const period=editingPeriod;if(!period)return;const warning=period.base?'这是美柚导入的历史记录。确认取消整次记录？':'确认取消这次月经记录？';if(confirm(warning)){document.querySelector('#dayDialog').close();removePeriodRecord(period)}});
document.querySelector('#dailyForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),date=f.get('date');state.logs[date]={mood:f.get('mood'),energy:f.get('energy'),sleep:f.get('sleep'),activity:f.get('activity'),pain:f.get('pain'),stress:f.get('stress'),symptoms:f.getAll('symptom'),temperature:f.get('temperature'),updatedAt:nowIso()};saveLocal();document.querySelector('#logDialog').close();showToast('当天记录已保存')});
document.querySelector('#optionalToggle').addEventListener('click',()=>{const toggle=document.querySelector('#optionalToggle'),fields=document.querySelector('#optionalFields'),open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));fields.hidden=open;toggle.querySelector('.optional-toggle-icon').textContent=open?'＋':'－';if(!open)fields.scrollIntoView({block:'nearest'})});
document.querySelector('#deleteLogBtn').addEventListener('click',()=>{const date=document.querySelector('#dailyForm').elements.date.value;if(state.logs[date]&&confirm(`删除 ${date} 的身体记录？可在短时间内撤销。`)){const old=state.logs[date],at=nowIso();delete state.logs[date];state.tombstones.logs[date]=at;saveLocal();document.querySelector('#logDialog').close();showUndo('身体记录已删除',()=>{state.logs[date]={...old,updatedAt:nowIso()};delete state.tombstones.logs[date];saveLocal()})}});
function showUndo(message,undo){const t=document.querySelector('#toast');t.innerHTML=`${message} <button id="undoBtn" class="text-button">撤销</button>`;t.classList.add('show');const timer=setTimeout(()=>{t.classList.remove('show');t.textContent=''},5000);document.querySelector('#undoBtn').onclick=()=>{clearTimeout(timer);undo();t.classList.remove('show');showToast('已撤销')}}
document.querySelector('#calendarGrid').addEventListener('click',()=>{});document.querySelector('#prevMonth').addEventListener('click',()=>{calendarCursor.setMonth(calendarCursor.getMonth()-1);renderCalendar()});document.querySelector('#nextMonth').addEventListener('click',()=>{calendarCursor.setMonth(calendarCursor.getMonth()+1);renderCalendar()});
document.querySelector('#historyList').addEventListener('click',e=>{const b=e.target.closest('.edit-period');if(!b)return;const p=allPeriods().find(x=>x.start===b.dataset.start);if(p)openPeriodEditor(p)});
document.querySelector('#dayEditLog').addEventListener('click',()=>{document.querySelector('#dayDialog').close();openLog(selectedDate)});
document.querySelector('#lifeStage').addEventListener('change',e=>{settings.lifeStage=e.target.value;saveSettings();renderAll()});document.querySelector('#ownerNotify').addEventListener('change',e=>{settings.ownerNotify=e.target.checked;saveSettings()});document.querySelector('#partnerNotify').addEventListener('change',e=>{settings.partnerNotify=e.target.checked;saveSettings()});
document.querySelector('#savePasscode').addEventListener('click',async()=>{const v=document.querySelector('#editPasscode').value;if(v.length<12)return showToast('编辑口令至少12位，建议16–24位');try{await authorizeDevice(v);document.querySelector('#editPasscode').value='';renderSettings();showToast('本设备已验证，180天内无需重复输入')}catch(e){showToast(e.message)}});document.querySelector('#forgetDeviceBtn').addEventListener('click',()=>{localStorage.removeItem(DEVICE_TOKEN_KEY);localStorage.removeItem(DEVICE_TOKEN_EXPIRY_KEY);localStorage.removeItem('period-editor-device');renderSettings();showToast('已忘记设备验证')});
document.querySelector('#exportBtn').addEventListener('click',()=>{const payload={schemaVersion:2,exportedAt:nowIso(),periods:allPeriods(),logs:state.logs,tombstones:state.tombstones,settings};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download=`period-backup-${iso(new Date())}.json`;a.click();URL.revokeObjectURL(a.href)});
document.querySelector('#importInput').addEventListener('change',async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(![1,2].includes(d.schemaVersion)||!Array.isArray(d.periods))throw Error();state=normalizeState({periods:d.periods.filter(p=>p.source!=='美柚截图'),logs:d.logs,tombstones:d.tombstones});saveLocal();showToast('备份已导入')}catch{showToast('备份文件格式不正确')}});
document.querySelector('#resetLocalBtn').addEventListener('click',()=>{if(!confirm('删除全部本设备新增记录并同步删除？美柚历史不会删除。'))return;const at=nowIso();state.periods.forEach(p=>state.tombstones.periods[periodKey(p)]=at);Object.keys(state.logs).forEach(d=>state.tombstones.logs[d]=at);state.periods=[];state.logs={};saveLocal()});
window.addEventListener('online',()=>{renderSettings();pullRemote();if(localStorage.getItem(SYNC_PENDING_KEY)==='yes')syncNow()});window.addEventListener('offline',()=>{renderSettings();setSync('离线保存')});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;document.querySelector('#installBtn').hidden=false});document.querySelector('#installBtn').addEventListener('click',async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;document.querySelector('#installBtn').hidden=true}});window.addEventListener('appinstalled',renderSettings);

function renderCalendarEnhanced(){const y=calendarCursor.getFullYear(),mo=calendarCursor.getMonth(),today=iso(new Date()),periods=allPeriods();document.querySelector('#calendarYearSelect').innerHTML=Array.from({length:new Date().getFullYear()-2014+2},(_,i)=>2014+i).map(v=>`<option value="${v}" ${v===y?'selected':''}>${v}年</option>`).join('');document.querySelector('#monthViewBtn').classList.toggle('active',calendarMode==='month');document.querySelector('#yearViewBtn').classList.toggle('active',calendarMode==='year');document.querySelector('.weekdays').hidden=calendarMode==='year';const grid=document.querySelector('#calendarGrid');if(calendarMode==='year'){document.querySelector('#calendarTitle').textContent=`${y}年`;grid.className='calendar-grid year-grid';grid.innerHTML=Array.from({length:12},(_,m)=>{const count=new Date(y,m+1,0).getDate(),offset=new Date(y,m,1).getDay();let cells='<span></span>'.repeat(offset);for(let d=1;d<=count;d++){const key=iso(new Date(y,m,d)),period=prioritizePeriods(periods.filter(x=>inRange(key,x.start,x.end)))[0],recorded=!!period,hasData=Boolean(state.logs[key]);cells+=`<button class="mini-day${recorded?' recorded':''}${period?.start===key?' period-start':''}${period?.end===key?' period-end':''}${hasData?' has-data':''}${key===today?' today':''}" data-date="${key}" aria-label="${key}${period?.start===key?' 月经开始':''}${period?.end===key?' 月经结束':''}">${d}</button>`}return `<section class="mini-month"><h3>${m+1}月</h3><div class="mini-days">${cells}</div></section>`}).join('');return}document.querySelector('#calendarTitle').textContent=`${y}年${mo+1}月`;grid.className='calendar-grid';const first=new Date(y,mo,1),start=new Date(y,mo,1-first.getDay()),p=phaseInfo();let html='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=iso(d),period=prioritizePeriods(periods.filter(x=>inRange(key,x.start,x.end)))[0],classes=['day',`phase-${phaseForDate(key)}`];if(d.getMonth()!==mo)classes.push('outside');if(key===today)classes.push('today');if(period){classes.push('recorded');if(period.start===key)classes.push('period-start');if(period.end===key)classes.push('period-end')}else if(inRange(key,p.windowStart,p.windowEnd))classes.push('predicted');html+=`<button class="${classes.join(' ')}" data-date="${key}" aria-label="${key}${period?.start===key?' 月经开始':''}${period?.end===key?' 月经结束':''}"><span class="day-number">${d.getDate()}</span></button>`}grid.innerHTML=html}

function explainCyclePoint(index){const item=cycleModel().intervals[index];if(!item)return;const end=addDays(item.start,item.length-1),status=item.length<21?'短于21天参考下限':item.length>35?'长于35天参考上限':'位于21–35天参考范围内';document.querySelector('#cyclePointDetail').innerHTML=`<strong>${item.start} → ${end}</strong><br>该周期为 <strong>${item.length}天</strong>，${status}。周期长度按本次月经首日至下次月经首日计算；单次变化只能用于记录趋势，不代表诊断。`}

document.querySelector('#monthViewBtn').addEventListener('click',()=>{calendarMode='month';renderCalendarEnhanced()});document.querySelector('#yearViewBtn').addEventListener('click',()=>{calendarMode='year';renderCalendarEnhanced()});document.querySelector('#calendarYearSelect').addEventListener('change',e=>{calendarCursor.setFullYear(Number(e.target.value));renderCalendarEnhanced()});document.querySelector('#prevMonth').addEventListener('click',e=>{if(calendarMode!=='year')return;e.stopImmediatePropagation();calendarCursor.setFullYear(calendarCursor.getFullYear()-1);renderCalendarEnhanced()},true);document.querySelector('#nextMonth').addEventListener('click',e=>{if(calendarMode!=='year')return;e.stopImmediatePropagation();calendarCursor.setFullYear(calendarCursor.getFullYear()+1);renderCalendarEnhanced()},true);document.querySelector('#calendarGrid').addEventListener('click',e=>{const d=e.target.closest('.mini-day[data-date]');if(d)showDay(d.dataset.date)});document.querySelector('#cycleHistoryChart').addEventListener('click',e=>{const p=e.target.closest('circle[data-cycle-index]');if(p)explainCyclePoint(Number(p.dataset.cycleIndex))});document.querySelector('#cycleHistoryChart').addEventListener('keydown',e=>{const p=e.target.closest('circle[data-cycle-index]');if(p&&(e.key==='Enter'||e.key===' ')){e.preventDefault();explainCyclePoint(Number(p.dataset.cycleIndex))}});

if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
try{await loadBase();await pullRemote();renderAll();checkStatus();const hash=location.hash.slice(1);if(['today','calendar','insights','more'].includes(hash))showView(hash);if(localStorage.getItem(SYNC_PENDING_KEY)==='yes')scheduleSync()}catch(e){alertSystem('页面数据载入失败，请联网刷新或检查数据文件。','danger');safeLog('startup',e.name||'failed')}
